import { StyleSheet, Dimensions } from 'react-native';
import colors from './colors';
import { radius, spacing } from './spacing';

const { width, height } = Dimensions.get('window');

const layout = StyleSheet.create({
  cardLg: {
    width: width,
    height: height * 0.8,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xxl,
  },
  cardMd: {
    width: width,
    height: height * 0.65,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xl,
  },
  cardSm: {
    width: width,
    height: height * 0.35,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xl,
  },
  cardXs: {
    width: width,
    height: height * 0.25,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xl,
  },
  cardXxs: {
    width: width,
    height: height * 0.18,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xl,
  },
  cardXxxs: {
    width: width,
    height: height * 0.12,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xl,
  },
  cardSlit: {
    width: width,
    height: height * 0.08,
    justifyContent: 'center',
    backgroundColor: colors.neutral,
    padding: spacing.xl,
  },
  cardLgTertiary: {
    width: width,
    height: height,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xxl,
  },
  cardMdTertiary: {
    width: width,
    height: height * 0.55,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xl,
  },
  cardSmTertiary: {
    width: width,
    height: height * 0.35,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xl,
  },
  cardXsTertiary: {
    width: width,
    height: height * 0.25,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xl,
  },
  cardXxsTertiary: {
    width: width,
    height: height * 0.18,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xl,
  },
  cardXxxsTertiary: {
    width: width,
    height: height * 0.12,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xl,
  },
  cardSlitTertiary: {
    width: width,
    height: height * 0.08,
    justifyContent: 'center',
    backgroundColor: colors.tertiary,
    padding: spacing.xl,
  },
  cardLgDark: {
    flex: 1,
    justifyContent: 'center',
    width: width,
    height: height,
    backgroundColor: colors.bg,
    padding: spacing.xxl,
  },
  cardMdDark: {
    flex: 1,
    justifyContent: 'center',
    width: width,
    height: height * 0.55,
    backgroundColor: colors.bg,
    borderColor: colors.secondary,
    padding: spacing.xl,
  },
  cardSmDark: {
    flex: 1,
    justifyContent: 'center',
    marginVertical: spacing.xl,
    width: width,
    height: height * 0.3,
    backgroundColor: colors.bg,
    padding: spacing.xl,
  },
  cardXsDark: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: spacing.xl,
    width: width,
    height: height * 0.25,
    backgroundColor: colors.bg,
    padding: spacing.xl,
  },
  cardXxsDark: {
    flex: 1,
    justifyContent: 'center',
    marginVertical: spacing.xl,
    width: width,
    height: height * 0.18,
    backgroundColor: colors.bg,
    padding: spacing.xl,
  },
  cardXxxsDark: {
    flex: 1,
    justifyContent: 'center',
    marginVertical: spacing.xl,
    width: width,
    height: height * 0.12,
    backgroundColor: colors.bg,
    padding: spacing.xl,
  },
  cardSlitDark: {
    flex: 1,
    justifyContent: 'center',
    marginVertical: spacing.xl,
    width: width,
    height: height * 0.08,
    backgroundColor: colors.bg,
    padding: spacing.xl,
  },
});

export default layout;